In [1]:
import pandas as pd
import numpy as np
import re
import datetime

In [2]:
df = pd.read_csv('data_craigslist.csv').drop(columns=['Unnamed: 0', 'level_0', 'index','Date'])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2938 entries, 0 to 2937
Data columns (total 19 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   Price                   2938 non-null   float64
 1   Neighborhood            2938 non-null   object 
 2   URL                     2938 non-null   object 
 3   bicycle frame material  1864 non-null   object 
 4   bicycle type            1864 non-null   object 
 5   frame size              1749 non-null   object 
 6   suspension              829 non-null    object 
 7   wheel size              1749 non-null   object 
 8   num image               2938 non-null   int64  
 9   text                    2600 non-null   object 
 10  condition               1380 non-null   object 
 11  electric assist         575 non-null    object 
 12  make / manufacturer     1173 non-null   object 
 13  model name / number     713 non-null    object 
 14  brake type              667 non-null    

In [3]:
df.head()

Price     Neighborhood                                                URL  \
0  1900.0     (Hudson, FL)  https://newyork.craigslist.org/brk/bik/d/hudso...   
1   300.0   (Fairfield CT)  https://newyork.craigslist.org/fct/bik/d/fairf...   
2   190.0       (BROOKLYN)  https://newyork.craigslist.org/brk/bik/d/brook...   
3   250.0   (West Village)  https://newyork.craigslist.org/mnh/bik/d/new-y...   
4   800.0       (Brooklyn)  https://newyork.craigslist.org/brk/bik/d/brook...   

  bicycle frame material bicycle type frame size suspension wheel size  \
0                    NaN          NaN        NaN        NaN        NaN   
1                    NaN          NaN        NaN        NaN        NaN   
2                    NaN          NaN        NaN        NaN        NaN   
3                    NaN          NaN        NaN        NaN        NaN   
4                    NaN          NaN        NaN        NaN        NaN   

   num image text condition electric assist make / manufacturer  \
0          0  NaN       NaN             NaN                 NaN   
1          0  NaN       NaN             NaN                 NaN   
2          0  NaN       NaN             NaN                 NaN   
3          0  NaN       NaN             NaN                 NaN   
4          0  NaN       NaN             NaN                 NaN   

  model name / number brake type handlebar type part type size / dimensions  \
0                 NaN        NaN            NaN       NaN               NaN   
1                 NaN        NaN            NaN       NaN               NaN   
2                 NaN        NaN            NaN       NaN               NaN   
3                 NaN        NaN            NaN       NaN               NaN   
4                 NaN        NaN            NaN       NaN               NaN   

  serial number  
0           NaN  
1           NaN  
2           NaN  
3           NaN  
4           NaN

In [4]:
df['Neighborhood'] = df['Neighborhood'].apply(lambda x:str(x)[2:(len(x)-1)].lower())

In [5]:
df

Price        Neighborhood  \
0     1900.0          hudson, fl   
1      300.0        fairfield ct   
2      190.0            brooklyn   
3      250.0        west village   
4      800.0            brooklyn   
...      ...                 ...   
2933   999.0  financial district   
2934  3850.0            brooklyn   
2935   125.0         garden city   
2936   190.0            brooklyn   
2937   250.0        west village   

                                                    URL  \
0     https://newyork.craigslist.org/brk/bik/d/hudso...   
1     https://newyork.craigslist.org/fct/bik/d/fairf...   
2     https://newyork.craigslist.org/brk/bik/d/brook...   
3     https://newyork.craigslist.org/mnh/bik/d/new-y...   
4     https://newyork.craigslist.org/brk/bik/d/brook...   
...                                                 ...   
2933  https://newyork.craigslist.org/mnh/bik/d/new-y...   
2934  https://newyork.craigslist.org/brk/bik/d/brook...   
2935  https://newyork.craigslist.org/lgi/bik/d/new-h...   
2936  https://newyork.craigslist.org/brk/bik/d/brook...   
2937  https://newyork.craigslist.org/mnh/bik/d/new-y...   

     bicycle frame material bicycle type frame size  \
0                       NaN          NaN        NaN   
1                       NaN          NaN        NaN   
2                       NaN          NaN        NaN   
3                       NaN          NaN        NaN   
4                       NaN          NaN        NaN   
...                     ...          ...        ...   
2933               aluminum          bmx        ALL   
2934                  steel       gravel         XL   
2935          other/unknown          bmx     Medium   
2936          other/unknown        track         54   
2937                  steel        other     Medium   

                             suspension wheel size  num image  \
0                                   NaN        NaN          0   
1                                   NaN        NaN          0   
2                                   NaN        NaN          0   
3                                   NaN        NaN          0   
4                                   NaN        NaN          0   
...                                 ...        ...        ...   
2933                                NaN      29 in          7   
2934                                NaN    27.5 in          0   
2935                                NaN      20 in          9   
2936                                NaN       700C          0   
2937   frame and fork (full suspension)       700C          3   

                                                   text condition  \
0                                                   NaN       NaN   
1                                                   NaN       NaN   
2                                                   NaN       NaN   
3                                                   NaN       NaN   
4                                                   NaN       NaN   
...                                                 ...       ...   
2933  The PK Ripper was the raddest, baddest, and mo...       new   
2934  I ordered this bike back in NOV.2020 with all ...       NaN   
2935  Haro F3 BMX-$175  Mongoose Racer X BMX-$175  T...       NaN   
2936  Pick up in Brooklyn 11229 show contact info  N...       NaN   
2937  1 red mountain bike, 1 black single speed,  bl...       NaN   

     electric assist make / manufacturer model name / number brake type  \
0                NaN                 NaN                 NaN        NaN   
1                NaN                 NaN                 NaN        NaN   
2                NaN                 NaN                 NaN        NaN   
3                NaN                 NaN                 NaN        NaN   
4                NaN                 NaN                 NaN        NaN   
...              ...                 ...                 ...        ...   
2933             NaN                 NaN                 NaN        N

In [6]:
df['bicycle frame material'].unique()

array([nan, ' steel', ' titanium', ' other/unknown', ' aluminum',
       ' alloy', ' carbon fiber', ' composite'], dtype=object)

In [7]:
def fix_bfm(x):
    if pd.isna(x) or x.strip() == 'other/unknown':
        return 'other/unknown'
    else:
        return x.strip()

df['bicycle frame material'] = df['bicycle frame material'].apply(fix_bfm)

In [8]:
df

Price        Neighborhood  \
0     1900.0          hudson, fl   
1      300.0        fairfield ct   
2      190.0            brooklyn   
3      250.0        west village   
4      800.0            brooklyn   
...      ...                 ...   
2933   999.0  financial district   
2934  3850.0            brooklyn   
2935   125.0         garden city   
2936   190.0            brooklyn   
2937   250.0        west village   

                                                    URL  \
0     https://newyork.craigslist.org/brk/bik/d/hudso...   
1     https://newyork.craigslist.org/fct/bik/d/fairf...   
2     https://newyork.craigslist.org/brk/bik/d/brook...   
3     https://newyork.craigslist.org/mnh/bik/d/new-y...   
4     https://newyork.craigslist.org/brk/bik/d/brook...   
...                                                 ...   
2933  https://newyork.craigslist.org/mnh/bik/d/new-y...   
2934  https://newyork.craigslist.org/brk/bik/d/brook...   
2935  https://newyork.craigslist.org/lgi/bik/d/new-h...   
2936  https://newyork.craigslist.org/brk/bik/d/brook...   
2937  https://newyork.craigslist.org/mnh/bik/d/new-y...   

     bicycle frame material bicycle type frame size  \
0             other/unknown          NaN        NaN   
1             other/unknown          NaN        NaN   
2             other/unknown          NaN        NaN   
3             other/unknown          NaN        NaN   
4             other/unknown          NaN        NaN   
...                     ...          ...        ...   
2933               aluminum          bmx        ALL   
2934                  steel       gravel         XL   
2935          other/unknown          bmx     Medium   
2936          other/unknown        track         54   
2937                  steel        other     Medium   

                             suspension wheel size  num image  \
0                                   NaN        NaN          0   
1                                   NaN        NaN          0   
2                                   NaN        NaN          0   
3                                   NaN        NaN          0   
4                                   NaN        NaN          0   
...                                 ...        ...        ...   
2933                                NaN      29 in          7   
2934                                NaN    27.5 in          0   
2935                                NaN      20 in          9   
2936                                NaN       700C          0   
2937   frame and fork (full suspension)       700C          3   

                                                   text condition  \
0                                                   NaN       NaN   
1                                                   NaN       NaN   
2                                                   NaN       NaN   
3                                                   NaN       NaN   
4                                                   NaN       NaN   
...                                                 ...       ...   
2933  The PK Ripper was the raddest, baddest, and mo...       new   
2934  I ordered this bike back in NOV.2020 with all ...       NaN   
2935  Haro F3 BMX-$175  Mongoose Racer X BMX-$175  T...       NaN   
2936  Pick up in Brooklyn 11229 show contact info  N...       NaN   
2937  1 red mountain bike, 1 black single speed,  bl...       NaN   

     electric assist make / manufacturer model name / number brake type  \
0                NaN                 NaN                 NaN        NaN   
1                NaN                 NaN                 NaN        NaN   
2                NaN                 NaN                 NaN        NaN   
3                NaN                 NaN                 NaN        NaN   
4                NaN                 NaN                 NaN        NaN   
...              ...                 ...                 ...        ...   
2933             NaN                 NaN                 NaN        N

In [9]:
df['bicycle type'].unique()

array([nan, ' other', ' bmx', ' track', ' road', ' mountain',
       ' hybrid/comfort', ' kids', ' folding', ' cruiser', ' gravel',
       ' cargo/pedicab'], dtype=object)

In [10]:
def fix_bt(x):
    if pd.isna(x) or x.strip() == 'other':
        return 'other/unknown'
    else:
        return x.strip()

df['bicycle type'] = df['bicycle type'].apply(fix_bt)

In [11]:
df['frame size'].unique()

array([nan, ' Medium', " I don't know, standard", ' 19', ' 54',
       ' all sizes', ' 58cm', ' 54cm medium', ' 16.5"', ' 1', ' All',
       ' 20”', ' 24”', ' 20"', ' 19"', ' 36cm  - 14 inches', ' 17”',
       ' 20 inches', ' 56cm', ' 36 inches wide', ' 26”', ' 23.6',
       ' 20.75', ' 20 inch', ' 21 Inches', ' Varies', ' 50 cm?',
       ' 29 Inches', ' 26', ' Large and Medium', ' ALL',
       ' 16 in (40.64 cm)', ' all', ' unknown', ' 18"', ' various',
       ' Regular size', ' large', ' 16", 18", or 20"', ' XL'],
      dtype=object)

In [12]:
def fix_fs(x):
    if pd.isna(x):
        return 'other/unknown'
    numbers = re.findall(r'\d+', x)
    if len(numbers) == 0:
        if 'medium' in x.lower():
            return 'medium'
        elif 'large' in x.lower():
            return 'large'
        elif 'small' in x.lower():
            return 'small'
        else:
            return 'other/unknown'
    else:
        if '"' or "'" or 'inches' or 'inch' or 'in' in x.lower(): #it's in inches
            size = float(numbers[0]) # assume it's the first number
            if size < 16:
                return 'small'
            if size > 19:
                return 'large'
            else:
                return 'medium'
        else: #cm
            size = float(numbers[0])
            if size < 53:
                return 'small'
            if size > 56:
                return 'large'
            else:
                return 'medium'

df['frame size'] = df['frame size'].apply(fix_fs)

In [13]:
df['suspension'].unique()

array([nan, ' frame and fork (full suspension)', ' none (rigid)',
       ' other/unknown', ' suspension fork (hardtail)'], dtype=object)

In [14]:
def fix_s(x):
    if pd.isna(x):
        return 0
    if 'fork' in x.lower():
        return 1
    else:
        return 0

df['suspension'] = df['suspension'].apply(fix_s)

In [15]:
df['wheel size'].unique()

array([nan, ' 700C', ' 16 in', ' 20 in', ' other/unknown', ' 24 in',
       ' 26 in', ' 27 in', ' 29 in', ' 18 in', ' 12 in', ' 25 in',
       ' 27.5 in'], dtype=object)

In [16]:
def fix_ws(x):
    if pd.isna(x):
        return 'other/unknown'
    if x.strip() == '700C':
        return 29
    numbers = re.findall(r'\d+', x)
    if len(numbers)==0:
        return np.nan
    else:
        return int(numbers[0])

df['wheel size'] = df['wheel size'].apply(fix_ws)

In [17]:
df['condition'].unique()

array([nan, ' good', ' like new', ' excellent', ' new', ' fair'],
      dtype=object)

In [18]:
def fix_c(x):
    if pd.isna(x):
        return 'other/unknown'
    if 'good' in x:
        return 'good'
    if 'new' or 'excellent' in x:
        return 'excellent'
    if 'fair' in x:
        return 'fair'

df['condition'] = df['condition'].apply(fix_c)

In [19]:
df['electric assist'].unique()

array([nan, ' pedal assist', ' none', ' throttle'], dtype=object)

In [20]:
def fix_ea(x):
    if pd.isna(x) or 'none' in x:
        return 0
    else:
        return 1

df['electric assist'] = df['electric assist'].apply(fix_ea)

In [21]:
df['make / manufacturer'].unique()

array([nan, ' Velosolex', ' Mongoose', ' trek giant Bianchi vitus',
       ' raleigh trek schwinn giant', ' Saris', ' Trek,Cannondale,GT',
       ' Haro GT Dyno Mongoose SE', ' trek giant diamondback',
       ' trek schwinn raleigh giant', ' TREK', ' Zizzo', ' SE',
       ' trek giant fuji schwinn raleigh', ' schwin, Huffy', ' Coaster',
       ' Shimano', ' Metakoo', ' SE Bikes', ' GT Bikes', ' NYC Bikes',
       ' fuji trek giat specialized', ' Se Bikes', ' Dynacraft',
       ' Rad Power Bikes', ' trek fuji giant raleigh', ' RAD POWER BIKES',
       ' RAD', ' jamis trek giant schwinn', ' trek fuji panasonic',
       ' trek giant gary fisher', ' Cyberbike', ' James', ' SportRack',
       ' Kazam', ' Honda', ' various', " I don't know",
       ' Schwinn Spin Bikes', ' Greenstar Bikes'], dtype=object)

In [22]:
def fix_mm(x):
    if pd.isna(x) or 'various' in x.lower() or x=="I don't know": 
        return 'other/unknown'
    if 'trek' in x.lower():
        return 'trek'
    if 'mongoose' in x.lower():
        return 'mongoose'
    if 'se' in x.lower():
        return 'se'
    else:
        return x.strip().lower()

df['make / manufacturer'] = df['make / manufacturer'].apply(fix_mm)

In [23]:
df['model name / number'].unique()

array([nan, ' Hutch', ' Bones', " Matte Trek Black/Blazin' Orange",
       ' Via', ' Fat', ' Stretch Rack', ' 350 Venture', ' BR-R7000',
       ' Trak100', ' Freewheel', ' CG BIG RIPPER',
       ' 2021 Pro Performer 20"', ' The Ultimate New York Bike',
       ' City Grounds Big Flyer', ' Mountain bikes',
       ' Radmini Step Thru 2', ' RadMini4', ' Woody Bike Stand',
       ' Rack Roof Bike Carrier SR4882RP', ' WILDERNESS TRAIL BIKES',
       ' Goldwing 1500', ' various', ' Ninja', ' AC Power', ' EcoCross'],
      dtype=object)

In [24]:
df['brake type'].unique()

array([nan, ' other/unknown', ' u-brakes', ' gyro/bmx',
       ' disc (mechanical)', ' v-brakes', ' caliper', ' disc (hydraulic)',
       ' none'], dtype=object)

In [25]:
def fix_bt(x):
    if pd.isna(x) or 'other/unknown' in x.lower() or 'none' in x.lower():
        return 'other/unknown'
    else:
        return x.strip().lower()

df['brake type'] = df['brake type'].apply(fix_bt)

In [26]:
df['handlebar type'].unique()

array([nan, ' drop', ' other/unknown', ' flat', ' bmx', ' riser'],
      dtype=object)

In [27]:
def fix_ht(x):
    if pd.isna(x) or 'other/unknown' in x:
        return 'other/unknown'
    else:
        return x.strip().lower()

df['handlebar type'] = df['handlebar type'].apply(fix_ht)

In [28]:
df['part type'].unique()

array([nan, ' other', ' racks, fenders, bags', ' brakes', ' saddle'],
      dtype=object)

In [29]:
def fix_pt(x):
    if pd.isna(x) or 'other' in x:
        return 0
    else:
        return 1

df['part type'] = df['part type'].apply(fix_pt)
df = df.where(df['part type']==0).dropna(how='all').drop(columns=['part type'])

In [30]:
df = df.drop(columns=['size / dimensions', 'serial number'])

In [31]:
df.columns = [column.replace(' ', '') for column in df.columns]

In [34]:
#df['days'] = [(datetime.datetime.today()-datetime.datetime.strptime(date_, "%Y-%m-%d %H:%M")).days for date_ in df['Date']]

In [35]:
df.drop_duplicates(subset=None, keep='first', inplace=False).to_csv('preprocessed_data_craigslist.csv')

In [36]:
df.drop_duplicates(subset=None, keep='first', inplace=False)



Price        Neighborhood  \
0    1900.0          hudson, fl   
1     300.0        fairfield ct   
2     190.0            brooklyn   
3     250.0        west village   
4     800.0            brooklyn   
..      ...                 ...   
446   275.0               11231   
447   999.0  financial district   
448  3850.0            brooklyn   
449   125.0         garden city   
450   190.0            brooklyn   

                                                   URL bicycleframematerial  \
0    https://newyork.craigslist.org/brk/bik/d/hudso...        other/unknown   
1    https://newyork.craigslist.org/fct/bik/d/fairf...        other/unknown   
2    https://newyork.craigslist.org/brk/bik/d/brook...        other/unknown   
3    https://newyork.craigslist.org/mnh/bik/d/new-y...        other/unknown   
4    https://newyork.craigslist.org/brk/bik/d/brook...        other/unknown   
..                                                 ...                  ...   
446  https://newyork.craigslist.org/brk/bik/d/brook...        other/unknown   
447  https://newyork.craigslist.org/mnh/bik/d/new-y...             aluminum   
448  https://newyork.craigslist.org/brk/bik/d/brook...                steel   
449  https://newyork.craigslist.org/lgi/bik/d/new-h...        other/unknown   
450  https://newyork.craigslist.org/brk/bik/d/brook...        other/unknown   

        bicycletype      framesize  suspension      wheelsize  numimage  \
0     other/unknown  other/unknown         0.0  other/unknown       0.0   
1     other/unknown  other/unknown         0.0  other/unknown       0.0   
2     other/unknown  other/unknown         0.0  other/unknown       0.0   
3     other/unknown  other/unknown         0.0  other/unknown       0.0   
4     other/unknown  other/unknown         0.0  other/unknown       0.0   
..              ...            ...         ...            ...       ...   
446  hybrid/comfort  other/unknown         0.0  other/unknown      10.0   
447             bmx  other/unknown         0.0             29       7.0   
448          gravel  other/unknown         0.0             27       0.0   
449             bmx         medium         0.0             20       9.0   
450           track          large         0.0             29       0.0   

                                                  text      condition  \
0                                                  NaN  other/unknown   
1                                                  NaN  other/unknown   
2                                                  NaN  other/unknown   
3                                                  NaN  other/unknown   
4                                                  NaN  other/unknown   
..                                                 ...            ...   
446  I have one in each size, 16", 18", and 20". Th...      excellent   
447  The PK Ripper was the raddest, baddest, and mo...      excellent   
448  I ordered this bike back in NOV.2020 with all ...  other/unknown   
449  Haro F3 BMX-$175  Mongoose Racer X BMX-$175  T...  other/unknown   
450  Pick up in Brooklyn 11229 show contact info  N...  other/unknown   

     electricassist make/manufacturer modelname/number      braketype  \
0               0.0     other/unknown              NaN  other/unknown   
1               0.0     other/unknown              NaN  other/unknown   
2               0.0     other/unknown              NaN  other/unknown   
3               0.0     other/unknown              NaN  other/unknown   
4               0.0     other/unknown              NaN  other/unknown   
..              ...               ...              ...            ...   
446             0.0     other/unknown              NaN  other/unknown   
447             0.0     other/unknown              NaN  other/unknown   
448             0.0     other/unknown              NaN  other/unknown   
449             0.0     other/unknown              NaN  other/unknown   
450             0.0     other/unknown              NaN 

In [ ]:
df