In [852]:
import pandas as pd
import numpy as np
import re
import datetime
from os.path import exists

In [853]:
places_raw = pd.read_excel('places.xlsx', header=None)
places = places_raw[0].values

In [854]:
index=0
for city in places:
    if exists('data_craigslist'+str(city)+'.csv'):
        if index == 0:
            df = pd.read_csv('data_craigslist'+str(city)+'.csv').drop(columns=['Unnamed: 0'])
            index += 1
        else:
            df = pd.concat([df, pd.read_csv('data_craigslist'+str(city)+'.csv').drop(columns=['Unnamed: 0'])], axis=0, ignore_index=True)

In [856]:
# Gets rid of the rows where we don't have any features
new_index = []
for ind in df.index:
    try:
        if df.loc[ind].count() >= 7:
            new_index.append(ind)
    except:
        pass

df = df.loc[new_index].reset_index(drop=True)

In [857]:
df.columns

Index(['Price', 'Location', 'URL', 'Date', 'Title', 'num image', 'text',
       'condition', 'make / manufacturer', 'model name / number',
       'bicycle frame material', 'bicycle type', 'brake type',
       'electric assist', 'frame size', 'handlebar type', 'suspension',
       'wheel size', 'size / dimensions', 'serial number', 'part type',
       'paint color', 'year manufactured', 'engine hours (total)',
       'length overall (LOA)', 'propulsion type'],
      dtype='object')

In [858]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2431 entries, 0 to 2430
Data columns (total 26 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   Price                   2431 non-null   float64
 1   Location                2431 non-null   object 
 2   URL                     2431 non-null   object 
 3   Date                    2431 non-null   object 
 4   Title                   2431 non-null   object 
 5   num image               2431 non-null   int64  
 6   text                    2431 non-null   object 
 7   condition               1104 non-null   object 
 8   make / manufacturer     952 non-null    object 
 9   model name / number     665 non-null    object 
 10  bicycle frame material  1131 non-null   object 
 11  bicycle type            1131 non-null   object 
 12  brake type              362 non-null    object 
 13  electric assist         262 non-null    object 
 14  frame size              1078 non-null   

In [859]:
print(df['bicycle frame material'].unique())

[nan ' aluminum' ' alloy' ' other/unknown' ' steel' ' carbon fiber'
 ' titanium' ' composite' ' scandium']


In [860]:
def fix_bfm(x):
    if pd.isna(x) or x.strip() == 'other/unknown':
        return 'unknown'
    else:
        return x.strip()

df['bicycle frame material'] = df['bicycle frame material'].apply(fix_bfm)

In [861]:
print(df['bicycle frame material'].unique())

['unknown' 'aluminum' 'alloy' 'steel' 'carbon fiber' 'titanium'
 'composite' 'scandium']


In [862]:
df['bicycle type'].unique()

array([nan, ' mountain', ' other', ' kids', ' hybrid/comfort', ' cruiser',
       ' bmx', ' road', ' unicycle', ' folding', ' gravel', ' track',
       ' cargo/pedicab', ' recumbent/trike', ' tandem'], dtype=object)

In [863]:
def fix_bt(x):
    if pd.isna(x) or x.strip() == 'other':
        return 'unknown'
    else:
        return x.strip()

df['bicycle type'] = df['bicycle type'].apply(fix_bt)

In [864]:
df['bicycle type'].unique()

array(['unknown', 'mountain', 'kids', 'hybrid/comfort', 'cruiser', 'bmx',
       'road', 'unicycle', 'folding', 'gravel', 'track', 'cargo/pedicab',
       'recumbent/trike', 'tandem'], dtype=object)

In [865]:
df['frame size'].unique()

array([nan, ' Medium', ' Large', ' 26 inch', ' Fits most bikes!',
       ' 12” wheels', ' 18', ' 0', ' 8"', ' 24”', ' All', ' 26" and 24"',
       ' medium', ' 19.5', ' any', ' 56cm', ' 54 cm, medium', ' 60cm',
       ' All sizes', ' 16 inch', ' unknown', ' N/A', ' Unknown', ' None',
       ' 15 inch', ' 60 cm', ' 18 "', ' 19in', ' 26 in',
       ' 42x40x10 inches', ' 52 cm', ' Any size', ' 15"', ' 18.5”',
       ' n/a', ' Kids size', ' 50cm', " Women's Medium", ' 20" wheels',
       ' 26in.', ' Medium/Large', ' small', ' Small', " don't reall know",
       ' 54cm medium17.5', ' Adult', ' good size', ' MEDIUM TO LARGE',
       ' 27"', ' 20"', ' XXL', ' 65cm', ' 18.25 in (46.35 cm)', ' 20',
       ' child size', ' 49 to 63 cm', ' 26”', ' 16', ' 26"', " 26'",
       ' 16”, 12”', ' 17.5', ' girls/kids', ' 16"MEDIUM & 20"LARGE',
       ' Various', ' 222', ' 29x29x29', ' Kids', ' See photo',
       ' Different sizes', ' 43cm', ' all sizes', ' All Sizes', ' cargo',
       ' 26', ' Ladies/Tee

In [866]:
def fix_fs(x):
    if pd.isna(x):
        return 'unknown'
    numbers = re.findall(r'\d+', x)
    if len(numbers) == 0:
        if 'medium' in x.lower():
            return 'medium'
        elif 'large' in x.lower():
            return 'large'
        elif 'small' in x.lower():
            return 'small'
        else:
            return 'unknown'
    else:
        if '"' or "'" or 'inches' or 'inch' or 'in' in x.lower(): #it's in inches
            size = float(numbers[0]) # assume it's the first number
            if size < 16:
                return 'small'
            if size > 19:
                return 'large'
            else:
                return 'medium'
        else: #cm
            size = float(numbers[0])
            if size < 53:
                return 'small'
            if size > 56:
                return 'large'
            else:
                return 'medium'

df['frame size'] = df['frame size'].apply(fix_fs)

In [867]:
df['frame size'].unique()

array(['unknown', 'medium', 'large', 'small'], dtype=object)

In [868]:
df['suspension'].unique()

array([nan, ' suspension fork (hardtail)', ' none (rigid)',
       ' other/unknown', ' frame and fork (full suspension)'],
      dtype=object)

In [869]:
def fix_s(x):
    if pd.isna(x):
        return 0
    if 'fork' in x.lower():
        return 1
    else:
        return 0

df['suspension'] = df['suspension'].apply(fix_s)

In [870]:
df['suspension'].unique()

array([0, 1], dtype=int64)

In [871]:
df['wheel size'].unique()

array([nan, ' 26 in', ' other/unknown', ' 12 in', ' 24 in', ' 20 in',
       ' 27 in', ' 700C', ' 25 in', ' 29 in', ' 14 in', ' 16 in',
       ' 10 in', ' 650B', ' 18 in', ' 27.5 in', ' 28 in', ' 26.5 in',
       ' 650C'], dtype=object)

In [872]:
def fix_ws(x):
    if pd.isna(x):
        return 'unknown'
    if '700' in x.strip():
        return 29
    if '650' in x.strip():
        return 26
    numbers = re.findall(r'\d+', x)
    if len(numbers)==0:
        return 'unknown'
    else:
        if int(numbers[0]) > 30:
            return 'unknown'
        else:
            return int(numbers[0])

df['wheel size'] = df['wheel size'].apply(fix_ws)

In [873]:
df['wheel size'].unique()

array(['unknown', 26, 12, 24, 20, 27, 29, 25, 14, 16, 10, 18, 28],
      dtype=object)

In [874]:
df['condition'].unique()

array([nan, ' excellent', ' new', ' good', ' salvage', ' like new',
       ' fair'], dtype=object)

In [875]:
def fix_c(x):
    if pd.isna(x):
        return 'unknown'
    x = str(x)
    if 'good' in x:
        return 'good'
    if 'fair' in x:
        return 'fair'
    if 'salvage' in x or 'poor' in x:
        return 'poor'
    if 'new' or 'excellent' in x:
        return 'excellent'
    
    return 'unknown'


df['condition'] = df['condition'].apply(fix_c)

In [876]:
df['condition'].unique()

array(['unknown', 'excellent', 'good', 'poor', 'fair'], dtype=object)

In [877]:
df['electric assist'].unique()

array([nan, ' none', ' other', ' throttle', ' pedal assist'], dtype=object)

In [878]:
def fix_ea(x):
    if pd.isna(x):
        return 0
    x = str(x)
    if 'other' in x or 'none' in x:
        return 0
    return 1

df['electric assist'] = df['electric assist'].apply(fix_ea)

In [879]:
df['electric assist'].unique()

array([0, 1], dtype=int64)

In [880]:
df['make / manufacturer'].unique()

array([nan, ' Thule', ' BodyKore', ' Trek', ' Huffy', ' Diamondback',
       ' joystar', ' critical', ' huffy', ' SE Bikes', ' Saris',
       ' Royce Union, Huffy', ' Kent', ' Real tree', ' Cyberbike',
       ' all makes', ' NS Bikes', ' Fuji', ' Allen', ' Schwinn', ' Sun',
       ' Marin', ' Sole', ' Specialized', ' Life Fitness, Cybex, Hammer',
       ' Yakima', ' HUSQVARNA', ' Gatormade Trailers', ' roadmaster',
       ' Orbea', ' Bikemate', ' Suzuki', ' Viathon', ' Harley Davidson',
       ' Tony Hawk', ' Scott', ' Stamina', ' central bike', ' Litespeed',
       ' Jamis', ' mongoose', ' Rollfast', ' Giant', ' Windsor',
       ' Coleman', ' Rad Power Bikes', ' Maxxhaul', ' Dynacraft',
       ' grabber', ' Sears, JC Higgins', ' Salsa', ' Rad Power Bike',
       ' BMX', ' Hollywood', ' Triton', ' CUB CADET', ' BASS CAT',
       ' hotwheels', ' Charge Bikes', ' Free Spirit', ' All', ' Gibson',
       ' Bjorn', ' Lamar Trailers', ' Yamaha', ' sixthreezero',
       ' Rock Solid Cargo', '

In [881]:
def fix_mm(x):
    if pd.isna(x) or 'unknown' in x.lower():
        return 0
    return 1

df['make / manufacturer'] = df['make / manufacturer'].apply(fix_mm)

In [882]:
df['make / manufacturer'].unique()

array([0, 1], dtype=int64)

In [883]:
df['model name / number'].unique()

array([nan, ' 961XT Speedway', ' G703', ' 4300', ' Comfort tek', ' cub',
       ' So Cal Flyer', ' Grand Slam/4', ' See description', ' Four Bike',
       ' Unknown', ' Holy', ' Ace 24', ' Panther', ' Bobcat Trail 4',
       ' SB900', ' Ruby Pro', ' Dr. Tray plus one', ' ZERO TURN MOWER',
       ' Hotshot/ Gooseneck Trailer', ' Hardrock', ' power', ' Alma Cup',
       ' Hotrock', ' Gxsr', ' M.1', ' Sportster SuperLow XL883',
       ' Duosonic 8053-38', ' CR1 Team', ' Elite', ' ben hur',
       ' Sabre Titanium', ' Ariel', ' Satellite', ' FastRoad SLR',
       ' Rascal', ' Wellington', ' CT200AB', ' RadRunner2', ' grabber',
       ' 8002114', ' Campeon', ' Rad Rover', ' Duo glide', ' MONGOOSE',
       ' 914XT', ' HR8000', ' 179 TRX', ' LT 42', ' PANTERA', ' na',
       ' Radwagon Caboose', ' Breeze', ' All', ' 83" x 14\'', ' WR 250F',
       " Around the Block Men's Cruiser", " 7' x 16' x 7'",
       ' Super Cycle Shuttle', ' gamefisher', ' Series 50', ' General',
       ' Juiced City S

In [884]:
def fix_mn(x):
    if pd.isna(x) or 'unknown' in x.lower():
        return 0
    return 1

df['model name / number'] = df['model name / number'].apply(fix_mn)

In [885]:
df['model name / number'].unique()

array([0, 1], dtype=int64)

In [886]:
df['brake type'].unique()

array([nan, ' cantilever', ' disc (mechanical)', ' caliper', ' none',
       ' other/unknown', ' coaster', ' disc (hydraulic)', ' gyro/bmx',
       ' v-brakes', ' u-brakes', ' hydraulic rim brakes'], dtype=object)

In [887]:
def fix_bt(x):
    if pd.isna(x) or 'other/unknown' in x.lower() or 'none' in x.lower():
        return 'unknown'
    else:
        x = str(x)
        if 'hydraulic' in x:
            return 'hydraulic'
        elif 'mechanical' in x:
            return 'mechanical'
        else:
            return 'special'

df['brake type'] = df['brake type'].apply(fix_bt)

In [888]:
df['brake type'].unique()

array(['unknown', 'special', 'mechanical', 'hydraulic'], dtype=object)

In [889]:
df['handlebar type'].unique()

array([nan, ' flat', ' bmx', ' other/unknown', ' drop', ' cruiser',
       ' triathlon', ' riser', ' downhill', ' bullhorn', ' aero'],
      dtype=object)

In [890]:
def fix_ht(x):
    if pd.isna(x) or 'other/unknown' in x:
        return 'unknown'
    else:
        return 'special'

df['handlebar type'] = df['handlebar type'].apply(fix_ht)

In [891]:
df['handlebar type'].unique()

array(['unknown', 'special'], dtype=object)

In [892]:
df['part type'].unique()

array([nan, ' other', ' racks, fenders, bags', ' grips, bar ends, tape',
       ' tires', ' wheels and wheel parts', ' saddle', ' brakes',
       ' pedals', ' headset, stem, spacers', ' frame only'], dtype=object)

In [893]:
def fix_pt(x):
    if pd.isna(x) or 'other' in x.lower():
        return 0
    else:
        return 1

df['part type'] = df['part type'].apply(fix_pt)
# Let's get rid of the listings about parts
df = df.where(df['part type']==0).dropna(how='all').drop(columns=['part type'])

In [894]:
df['size / dimensions'].unique()

array([nan, ' 1 1/4” hitch', ' 26.38 x 12.2 x 13.98',
       ' \u200e42 x 40 x 10 inches', ' 750', ' 56x9.5x4.5',
       ' 4-bike capacity', ' 168" X 86" X 0"', ' 192" X 84" X 0"',
       ' 168" X 83" X 0"', ' 52"', ' 3 Bike Rack', ' 2 bikes', ' Large',
       ' 36', ' 10.32 x 7.52 x 2.4 inches', ' 110" x 36" wide x 30" high',
       ' 20 inch', ' 26x4.7', ' All sizes& extra lightweight.',
       ' 4" long', ' All sizes & extra lightweight.', ' 20 18 3',
       ' 6  feet', ' 5 1/2”', ' ;quot;w x 15" d', ' 12x4',
       ' 12 X 9.5 X 10', ' 48”H X 25”W X 56”L', ' 3 bike carrier',
       ' any adult', ' any 20” 24” 26”', ' L36 x W14 and 17',
       ' 38.5 x 56 x 12', ' 22x10', ' 30″x 12″', ' 30 x 8 x 30 inches',
       ' 16"', ' M/L', ' 120 70 17', ' 27" x 8" x 12"',
       ' 240" X 82" X 0"', ' 144" X 76" X 0"', ' 240" X 102" X 0"',
       ' 240" X 83" X 0"', ' 192" X 84" X 75"', ' 120" X 60" X 0"',
       ' 192" X 102" X 75"', ' 16\'L x 6\'10" wide', ' 240" X 101" X 79"',
       ' 240" 

In [895]:
def fix_sd(x):
    if pd.isna(x):
        return 0
    else:
        return 1

df['size / dimensions'] = df['size / dimensions'].apply(fix_sd)

In [896]:
df['size / dimensions'].unique()

array([0, 1], dtype=int64)

In [897]:
df['paint color'].unique()

array([nan, ' black', ' custom', ' grey', ' white', ' silver', ' red'],
      dtype=object)

In [898]:
def fix_pc(x):
    if pd.isna(x):
        return 0
    else:
        return 1

df['paint color'] = df['paint color'].apply(fix_pc)

In [899]:
df['paint color'].unique()

array([0, 1], dtype=int64)

In [900]:
df['serial number'].unique()

array([nan, ' Unknown', ' F1068892', ' N/A', ' EN14872XINGING',
       ' TC19 222501', ' na', ' NSN not needed', ' M50', ' EZ-201304 468',
       ' 408 406 7864 cell', ' Var', ' Nome', ' 23-918', ' See Photos',
       ' none', ' unknown', ' EG010897', ' 00012345', ' .', ' various',
       ' Ninja 2021', ' Freestyle', ' ??', ' NA', ' WT0406C5218',
       ' WTU336CT0109R1207', ' N/a', ' 1234567890', ' CU5C21B3934',
       ' see photos'], dtype=object)

In [901]:
def fix_sn(x):
    if pd.isna(x) or 'unknown' in x.lower() or 'na' in x.lower() or 'none' in x.lower():
        return 0
    else:
        return 1

df['serial number'] = df['serial number'].apply(fix_sn)

In [902]:
df['serial number'].unique()

array([0, 1], dtype=int64)

In [903]:
df['year manufactured'].unique()

array([  nan, 2022., 2020., 2010., 1975., 2021., 2005., 2001., 2015.,
       2019., 2012., 2013., 2017., 2006.])

In [904]:
def fix_ym(x):
    if pd.isna(x):
        return 0
    else:
        return 1

df['year manufactured']=df['year manufactured'].apply(fix_ym)

In [905]:
df['year manufactured'].unique()

array([0, 1], dtype=int64)

In [906]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2388 entries, 0 to 2430
Data columns (total 25 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   Price                   2388 non-null   float64
 1   Location                2388 non-null   object 
 2   URL                     2388 non-null   object 
 3   Date                    2388 non-null   object 
 4   Title                   2388 non-null   object 
 5   num image               2388 non-null   float64
 6   text                    2388 non-null   object 
 7   condition               2388 non-null   object 
 8   make / manufacturer     2388 non-null   float64
 9   model name / number     2388 non-null   float64
 10  bicycle frame material  2388 non-null   object 
 11  bicycle type            2388 non-null   object 
 12  brake type              2388 non-null   object 
 13  electric assist         2388 non-null   float64
 14  frame size              2388 non-null   

In [907]:
df.columns

Index(['Price', 'Location', 'URL', 'Date', 'Title', 'num image', 'text',
       'condition', 'make / manufacturer', 'model name / number',
       'bicycle frame material', 'bicycle type', 'brake type',
       'electric assist', 'frame size', 'handlebar type', 'suspension',
       'wheel size', 'size / dimensions', 'serial number', 'paint color',
       'year manufactured', 'engine hours (total)', 'length overall (LOA)',
       'propulsion type'],
      dtype='object')

In [908]:
df = df.drop(columns=['length overall (LOA)', 'propulsion type', 'engine hours (total)'])

In [909]:
df.columns = [column.replace('/', '').lower().strip().replace(' ', '') for column in df.columns]

In [910]:
df.columns

Index(['price', 'location', 'url', 'date', 'title', 'numimage', 'text',
       'condition', 'makemanufacturer', 'modelnamenumber',
       'bicycleframematerial', 'bicycletype', 'braketype', 'electricassist',
       'framesize', 'handlebartype', 'suspension', 'wheelsize',
       'sizedimensions', 'serialnumber', 'paintcolor', 'yearmanufactured'],
      dtype='object')

In [911]:
df['days'] = [(datetime.datetime.today()-datetime.datetime.strptime(date_, "%Y-%m-%d %H:%M")).days for date_ in df['date']]

In [912]:
df.to_csv('preprocessed_data_craigslist.csv')